#' The tsExpKit package is a package that brings its own time series classes, based on the zoo classes, which are similar to the \code{xts} class.
#' It has functions to apply preprocessing such as partitioning for training and testing, 
#' normalization, and embedding, as well as functions to build time series repositories, containing various time series packages, 
#' and to store characteristics of the series in the repository. Furthermore, it also has abilities to run well-documented 
#' experiments, in sequential or parallelized ways.
#' 
#' The package is mainly used internally in our department for experimentation. However, as it may be useful also to other people we decided to 
#' release this version publicly on CRAN. Some parts are still work in progress, and some (small) parts may not make much sense without our infrastructure. 
#' If you have any problems or suggestions, please contact the package maintainer directly by email. Don't write to the R mailing lists or other 
#' internet forums, as it is probable that we won't read your comments there. 
#' 
#' To get started with the package, you may want to have a look at the demo's. Don't start them directly, but access them in the package source in 
#' the demo subfolder. You may need to adjust some paths etc. in order to get the demo's running. 
#' 
#' The attributed time series class \code{\link{aTS}} is basically a zoo object with its own mechanism for attributes, similar to \code{xts}. 
#' The reason for the custom implementation is that \code{xts} is very strict on the time stamps it allows, and it turned out that in many situations 
#' less strict time stamps, e.g., when having artificial time series or when performing preliminary experiments, are desirable.
#' 
#' Based on the \code{\link{aTS}} class is its subclass \code{\link{eTS}}, which is the embedded time series class. You can construct an \code{\link{eTS}} 
#' object from an \code{\link{aTS}} object simply by defining the embedding to use.
#' Both the \code{\link{aTS}} and the \code{\link{eTS}} classes have possibilities to perform normalization on them, to generate training and test 
#' partitions from them, etc. They also have a lot of convenience functions to get and set information the attributes that they store.
#' 
#' Based on these classes is the concept of the \code{\link{ATSList}}, which is the basis for the time series repository structure. 
#' It is simply a list of \code{\link{aTS}} objects. However, there 
#' exist many functions for batch processing that work directly on \code{\link{ATSList}}s, and to work with several series instead of single series.
#' Namely, there are the functions
#' \code{\link{setNamesATSList}}, \code{\link{summaryTableATSList}}, 
#' \code{\link{computePartitionsATSList}}, \code{\link{groupATSListByPartitions}}, and 
#' \code{\link{embedATSList}}. 
#' Furthermore, for I/O, there are: \code{\link{loadDifToATSList}}, 
#' \code{\link{loadDatDirToATSList}}, \code{\link{loadDataDirToATSList}}, \code{\link{loadATSDir}}, 
#' \code{\link{loadATSDir}}, \code{\link{saveATSList}}, \code{\link{savePlotsATSList}}, 
#' and \code{\link{saveAsDataPackageATSList}}. 
#' 
#' Using the \code{\link{ATSList}}, there are functions that work directly on aTS directories, which are \code{\link{ATSList}}s exported to disk.
#' Currently, there are the functions \code{\link{embedATSDir}}, \code{\link{partitionATSDir}}, and \code{\link{normalizeATSDir}} to work directly 
#' on aTS directories.
#' 
#' A time series data package is a hierarchical structure of ATS directories. Here, a data package, i.e., a package of time series, is stored in different versions
#' (preprocessing). Besides the ATS directory functions mentioned above, there is the function \code{\link{saveAsDataPackageATSList}}, which saves an \code{\link{ATSList}}
#' as an ATS directory, and generates summary tables and summary plots. Furthermore, there is the function \code{\link{importATSListIntoDataRepository}}, 
#' which is recommended when first importing data into a data repository. The summary tables generated by these functions contain characteristics of
#' the time series, such as descriptive statistical measures, results of stationarity and linearity tests, and data complexity measures.
#' In concrete, the import functions call one-line-summary functions, i.e., they call \code{\link{oneLineSummary}} which calls \code{\link{oneLineSummaryAll}}. This function then
#' calls the specific functions for the different kinds of summaries. Currently implemented are 
#' \code{\link{oneLineSummaryDescStat}}, \code{\link{oneLineSummaryOtherTests}}, and \code{\link{oneLineSummaryStatNonlin}}.
#' The data complexity measures should be implemented here. Either, by creating a new one-line-summary function so 
#' that an additional table is generated, or by simply adding them to the existing tables.
#'
#' Yet another important part of the package is the experimentation framework around the function \code{\link{runExperiments}}.
#' The functions \code{\link{genUsedData}}, \code{\link{initParallelMode}}, and \code{\link{assembleExperimentsPath}}
#' assist in setting up the experiments, and afterwards, the functions
#' \code{\link{evaluateModels}}, \code{\link{evaluatePredictions}}, \code{\link{plotPredictions}} perform the evaluation by generating various csv-files.
#' Afterwards, in order to assist in the analysis of these csv-files, there is currently the function \code{\link{assembleMeasureTable}}, but probably 
#' somewhen there will be more functionality assisting in this also.
#' 
#' Also, there are some functions present to artificially generate time series with certain characteristics, 
#' see \code{\link{simulateLinearTS}}, and \code{\link{simulateNonlinearTS}}.
#'   
#' A lot of helpful utility functions that solve unspecific common tasks as well as tasks that often have to be solved in relation to the use of the
#' package are present. Examples are: \code{\link{joinCSVFiles}}, \code{\link{rBindByColNames}}, \code{\link{cBindByRowNames}},
#' \code{\link{multiplyIntervalBoundaries}}, \code{\link{getFileNameFromPath}}, etc.
#'
# \tabular{ll}{
# Package: \tab tsExpKit\cr
# Type: \tab Package\cr
# Version: \tab 0.1\cr
# Date: \tab 2011-02-08\cr
# License: \tab GPL (>= 2)\cr
# LazyLoad: \tab yes\cr
# }
#
#' @name tsExpKit-package
#' @aliases tsExpKit
#' @docType package
#' @title Getting started with the tsExpKit package
#' @references
#' C. Bergmeir, J.M. Benítez, On the Use of Cross-validation for Time Series Predictor Evaluation. Information Sciences 191 (2012) 192-213.
#' 
# @encoding UTF-8
#' @author Christoph Bergmeir \email{c.bergmeir@@decsai.ugr.es} 
#' 
#' with José M. Benítez \email{j.m.benitez@@decsai.ugr.es}
#' 
#' DiCITS Lab, Sci2s group, DECSAI, University of Granada.
#' 
#' \url{http://dicits.ugr.es}, \url{http://sci2s.ugr.es}
#' 
# @exportPattern "^[[:alpha:]]+"
NULL

